"""Add monitoring and system setting models

Revision ID: 4bcbb7aee979
Revises: 20260414_0002
Create Date: 2026-04-18 12:47:57.747420
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4bcbb7aee979'
down_revision = '20260414_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_channels_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels'))
    )
    op.create_index(op.f('ix_channels_product_id'), 'channels', ['product_id'], unique=False)
    op.create_table('monitoring_sources',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_monitoring_sources_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitoring_sources'))
    )
    op.create_index(op.f('ix_monitoring_sources_product_id'), 'monitoring_sources', ['product_id'], unique=False)
    op.create_table('ingested_content',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['monitoring_sources.id'], name=op.f('fk_ingested_content_source_id_monitoring_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingested_content'))
    )
    op.create_index(op.f('ix_ingested_content_external_id'), 'ingested_content', ['external_id'], unique=False)
    op.create_index(op.f('ix_ingested_content_source_id'), 'ingested_content', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingested_content_source_id'), table_name='ingested_content')
    op.drop_index(op.f('ix_ingested_content_external_id'), table_name='ingested_content')
    op.drop_table('ingested_content')
    op.drop_index(op.f('ix_monitoring_sources_product_id'), table_name='monitoring_sources')
    op.drop_table('monitoring_sources')
    op.drop_index(op.f('ix_channels_product_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###

