"""add_system_settings_table

Revision ID: d3c297b7f0dd
Revises: 4bcbb7aee979
Create Date: 2026-04-19 20:26:15.247568
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd3c297b7f0dd'
down_revision = '4bcbb7aee979'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

